/* Full request workspace: pricing, sourcing progress and quotation controls. */
(() => {
  const e = (value) => String(value ?? "").replace(/[&<>'"]/g, (x) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[x]));
  const moneyLocal = (value) => new Intl.NumberFormat("az-AZ", { style: "currency", currency: "AZN", maximumFractionDigits: 2 }).format(Number(value) || 0);
  const decimalValue = (value) => { const raw = String(value ?? "").trim().replace(/\s/g, ""); if (!raw) return 0; const normalized = raw.includes(",") && raw.includes(".") ? (raw.lastIndexOf(",") > raw.lastIndexOf(".") ? raw.replace(/\./g, "").replace(",", ".") : raw.replace(/,/g, "")) : raw.replace(",", "."); const parsed = Number(normalized); return Number.isFinite(parsed) ? parsed : 0; };
  const twoDecimals = (value) => decimalValue(value).toFixed(2);
  const bindPriceFormatting = (refresh) => document.querySelectorAll(".source-cost,.source-margin").forEach((input) => { input.type = "text"; input.inputMode = "decimal"; input.value = twoDecimals(input.value); if (input.dataset.decimalBound) return; input.dataset.decimalBound = "1"; input.oninput = () => { if (input.value.includes(",")) input.value = input.value.replace(",", "."); refresh(); }; input.onblur = () => { input.value = twoDecimals(input.value); refresh(); }; });
  const detailFieldStyles = () => { if (document.querySelector("#detail-price-field-styles")) return; const style = document.createElement("style"); style.id = "detail-price-field-styles"; style.textContent = `.detail-prices input,.detail-prices select{width:100%;max-width:148px;height:38px;padding:8px 11px;border:1px solid #d5dfec;border-radius:10px;background:#fff;color:#24334c;font:inherit;font-size:13px;line-height:1;box-shadow:inset 0 1px 2px rgba(20,33,58,.03),0 2px 6px rgba(20,33,58,.04);transition:border-color .16s ease,box-shadow .16s ease,background-color .16s ease}.detail-prices input:hover,.detail-prices select:hover{border-color:#a9c2e4;background:#fbfdff}.detail-prices input:focus,.detail-prices select:focus{outline:none;border-color:#4d8eea;background:#fff;box-shadow:0 0 0 3px rgba(77,142,234,.14),0 2px 7px rgba(20,33,58,.06)}.detail-prices input::placeholder{color:#9aa7b9}.detail-prices td:nth-child(3) .source-supplier{max-width:170px}.detail-prices td:nth-child(4) .source-found{max-width:100px;text-align:right}.detail-prices td:nth-child(6) .source-cost,.detail-prices td:nth-child(7) .source-margin,.detail-prices td:nth-child(8) .source-sale{max-width:122px;text-align:right;font-variant-numeric:tabular-nums}.detail-prices .remove-detail{min-width:70px;height:38px;border-color:#e2e8f1;background:#fff;color:#53647c;font-size:12px}.detail-prices .remove-detail:hover{border-color:#efbec8;background:#fff5f6;color:#bd3045}.detail-prices+button#addDetailProduct,#addDetailProduct{border-color:#c9daf4;background:#f7faff;color:#2769b5;font-size:12px}.detail-prices+button#addDetailProduct:hover,#addDetailProduct:hover{border-color:#9bbbe8;background:#edf5ff}@media(max-width:900px){.detail-prices input,.detail-prices select{max-width:100%;height:36px}.detail-prices td:nth-child(3) .source-supplier,.detail-prices td:nth-child(4) .source-found,.detail-prices td:nth-child(6) .source-cost,.detail-prices td:nth-child(7) .source-margin,.detail-prices td:nth-child(8) .source-sale{max-width:100%}}`; document.head.appendChild(style); };
  const detailShellStyles = () => { if (document.querySelector("#detail-shell-field-styles")) return; const style = document.createElement("style"); style.id = "detail-shell-field-styles"; style.textContent = `#detailStatus,#applyMargin{height:38px;border:1px solid #d5dfec;border-radius:10px;background:#fff;color:#24334c;font:inherit;font-size:13px;line-height:1;box-shadow:0 2px 7px rgba(20,33,58,.04);transition:border-color .16s ease,box-shadow .16s ease,background-color .16s ease}#detailStatus{min-width:160px;padding:8px 12px}#applyMargin{width:92px;padding:8px 11px;text-align:right;font-variant-numeric:tabular-nums}#detailStatus:hover,#applyMargin:hover{border-color:#a9c2e4;background:#fbfdff}#detailStatus:focus,#applyMargin:focus{outline:none;border-color:#4d8eea;box-shadow:0 0 0 3px rgba(77,142,234,.14),0 2px 7px rgba(20,33,58,.06)}#applyAll{height:38px;border-radius:10px;padding:8px 14px;font-size:12px;white-space:nowrap}.detail-prices{border-collapse:separate;border-spacing:0 6px}.detail-prices thead th{padding:8px 9px}.detail-prices tbody tr{background:#fff}.detail-prices tbody td{padding:8px 9px;vertical-align:middle}.detail-prices tbody td:first-child{border-radius:10px 0 0 10px}.detail-prices tbody td:last-child{border-radius:0 10px 10px 0}.detail-prices tbody tr:hover{background:#fbfdff}@media(max-width:900px){#detailStatus{min-width:140px}.detail-prices tbody td{padding:6px 5px}}`; document.head.appendChild(style); };
  const suppliersLocal = ["Azeri Fasteners", "Caspian Trade", "Steel Supply", "Baku Industrial"];
  const options = (selected) => `<option value="">Təchizatçı seçin</option>${suppliersLocal.map((s) => `<option ${s === selected ? "selected" : ""}>${s}</option>`).join("")}`;
  const labels = { NEW: "Yeni", PRICING: "Qiymət hazırlanır", QUOTATION_SENT: "Təklif göndərilib", WAITING_CUSTOMER: "Müştəri gözlənilir", ACTIVE: "Aktiv", COMPLETED: "Tamamlandı", REJECTED: "İmtina edildi" };
  function fullDetail(id) {
    const request = db.requests.find((item) => item.id === id); if (!request) return;
    detailFieldStyles();
    detailShellStyles();
    page = "request-detail";
    const rows = request.items.map((item, index) => { const margin = Number(item.margin ?? (item.cost ? ((item.sale / item.cost) - 1) * 100 : 20)); return `<tr data-index="${index}"><td><b>${e(item.name)}</b><span class="muted">${item.unit || "ədəd"}</span></td><td><span class="qty-requested">${item.qty}</span></td><td><input class="source-supplier" value="${e(item.supplier || "")}" list="supplier-list" placeholder="Təchizatçı"></td><td><input class="source-found" type="number" min="0" max="${item.qty}" value="${item.sourced || 0}"></td><td><b class="source-left danger">${Math.max(0, item.qty - (item.sourced || 0))}</b></td><td><input class="source-cost" type="number" min="0" step="0.0001" value="${item.cost || ""}" placeholder="0.00"></td><td><input class="source-margin" type="number" min="0" step="0.1" value="${margin.toFixed(1)}"></td><td><b class="source-sale">${moneyLocal(item.sale || (item.cost || 0) * (1 + margin / 100))}</b></td><td><button class="secondary remove-detail" type="button">Sil</button></td></tr>`; }).join("");
    document.querySelector("#root").innerHTML = `<div class="content"><div class="head"><div><button class="secondary" id="backRequests">← Sorğulara qayıt</button><div class="eyebrow" style="margin-top:18px">SORĞU DETALI</div><h1>${e(request.id)}</h1><p>${e(request.customer)} · Məhsul qiymətləndirməsi və tədarük idarəetməsi</p></div><div style="display:flex;gap:8px"><button class="secondary" id="detailQuotation">Qiymət təklifi</button><button class="primary" id="detailSave">Yadda saxla</button></div></div><div class="cards" style="grid-template-columns:repeat(4,1fr)"><div class="card"><label>Status</label><div class="num" style="font-size:15px">${badge(request.status)}</div></div><div class="card"><label>Məhsul sayı</label><div class="num">${request.items.length}</div></div><div class="card"><label>Tələb olunan</label><div class="num">${request.items.reduce((s, i) => s + Number(i.qty || 0), 0)}</div></div><div class="card"><label>Tapılan</label><div id="detailFound" class="num">${request.items.reduce((s, i) => s + Number(i.sourced || 0), 0)}</div></div></div><div class="panel" style="margin-top:16px"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2>Qiymət və təchizat cədvəli</h2><p>Hər məhsul üzrə kimdən alınacağını, tapılan miqdarı və satış qiymətini daxil edin.</p></div><select id="detailStatus">${Object.entries(labels).map(([key, value]) => `<option value="${key}" ${request.status === key ? "selected" : ""}>${value}</option>`).join("")}</select></div><datalist id="supplier-list">${suppliersLocal.map((s) => `<option value="${s}">`).join("")}</datalist><div class="table-wrap"><table class="tbl detail-prices"><thead><tr><th>Məhsul</th><th>Tələb</th><th>Kimdən alınacaq?</th><th>Tapılan</th><th>Qalan</th><th>Alış qiyməti</th><th>Faiz</th><th>Satış qiyməti</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><button class="secondary" id="addDetailProduct" style="margin-top:13px">＋ Məhsul əlavə et</button><div id="detailTotal" class="result" style="margin-top:15px"></div></div><div class="grid" style="margin-top:16px"><div class="panel"><h2>Proses tarixçəsi</h2><div class="timeline">${(request.timeline || []).map((item) => `<div><b>${e(item)}</b><span class="muted">Bu gün</span></div>`).join("")}</div></div><div class="panel"><h2>Yoxlama qaydası</h2><p>Satış qiyməti = alış qiyməti + tətbiq edilən faiz.</p><p>Faizi bütün məhsullara tətbiq etmək üçün aşağıdakı dəyəri dəyişin.</p><div class="field" style="margin-top:12px"><label>Hamısına faiz tətbiq et</label><div style="display:flex;gap:8px"><input id="applyMargin" type="number" min="0" step="0.1" value="20"><button class="secondary" id="applyAll">Bütün məhsullara tətbiq et</button></div></div></div></div></div>`;
    const refresh = () => { let found = 0, costTotal = 0, saleTotal = 0; document.querySelectorAll(".detail-prices tbody tr").forEach((row) => { const qty = Number(row.querySelector(".qty-requested")?.textContent || row.querySelector(".new-qty")?.value || 0), source = Number(row.querySelector(".source-found")?.value || 0), cost = Number(row.querySelector(".source-cost")?.value || 0), margin = Number(row.querySelector(".source-margin")?.value || 0), sale = cost * (1 + margin / 100); found += source; costTotal += source * cost; saleTotal += source * sale; const left = row.querySelector(".source-left"); if (left) { left.textContent = Math.max(0, qty - source); left.className = `source-left ${source >= qty ? "found-ok" : "danger"}`; } const saleNode = row.querySelector(".source-sale"); if (saleNode) saleNode.textContent = moneyLocal(sale); }); const foundNode = document.querySelector("#detailFound"); if (foundNode) foundNode.textContent = found; const totalNode = document.querySelector("#detailTotal"); if (totalNode) totalNode.innerHTML = `<b>Tapılan maya: ${moneyLocal(costTotal)}</b> &nbsp; <b>Tapılan satış: ${moneyLocal(saleTotal)}</b> &nbsp; <b>Mənfəət: ${moneyLocal(saleTotal - costTotal)}</b>`; };
    const detailActions = document.querySelector("#detailSave")?.parentElement;
    if (detailActions && !document.querySelector("#detailDeleteRequest")) {
      detailActions.style.flexWrap = "wrap";
      const deleteButton = document.createElement("button");
      deleteButton.type = "button";
      deleteButton.id = "detailDeleteRequest";
      deleteButton.className = "danger-action";
      deleteButton.textContent = "Sorğunu sil";
      deleteButton.onclick = () => window.softDeleteRequest?.(request);
      detailActions.insertBefore(deleteButton, detailActions.firstElementChild);
    }
    document.querySelectorAll(".source-found,.source-cost,.source-margin").forEach((input) => input.oninput = refresh); bindPriceFormatting(refresh);
    const priceTable = document.querySelector(".detail-prices");
    priceTable?.addEventListener("input", (event) => { const input = event.target; if (!input.matches?.(".source-cost,.source-margin")) return; if (input.value.includes(",")) input.value = input.value.replace(",", "."); refresh(); });
    priceTable?.addEventListener("blur", (event) => { const input = event.target; if (input.matches?.(".source-cost,.source-margin")) { input.value = twoDecimals(input.value); refresh(); } }, true);
    refresh();
    document.querySelector("#backRequests").onclick = () => { page = "requests"; render(); };
    document.querySelector("#detailSave").onclick = () => { const next = []; for (const row of document.querySelectorAll(".detail-prices tbody tr")) { const index = Number(row.dataset.index), old = index >= 0 ? request.items[index] : {}, qty = Number(row.querySelector(".qty-requested")?.textContent || row.querySelector(".new-qty")?.value || 0), name = index >= 0 ? old.name : row.querySelector(".new-name")?.value.trim(); if (!name || !qty) return toast("Məhsul adı və miqdarı məcburidir."); const cost = decimalValue(row.querySelector(".source-cost")?.value || 0), margin = decimalValue(row.querySelector(".source-margin")?.value || 0); next.push({ ...old, name, qty, unit: old.unit || "ədəd", supplier: row.querySelector(".source-supplier")?.value || "", sourced: Math.min(qty, Number(row.querySelector(".source-found")?.value || 0)), cost, margin, sale: cost * (1 + margin / 100) }); } request.items = next; const status = document.querySelector("#detailStatus").value; if (status !== request.status) { request.status = status; request.timeline.push("Status dəyişdi: " + (labels[status] || status)); if (status === "ACTIVE") activate(request); } audit("PRICE_CHANGE", request.id); save(); render(); toast("Qiymət, faiz və təchizat məlumatları saxlanıldı"); };
    document.querySelector("#applyAll").onclick = () => { const margin = Number(document.querySelector("#applyMargin").value || 0); document.querySelectorAll(".source-margin").forEach((input) => { input.value = margin; }); refresh(); toast(`${margin}% bütün məhsullara tətbiq edildi`); };
    document.querySelector("#detailQuotation").onclick = () => { if ([...document.querySelectorAll(".source-sale")].some((node) => node.textContent.includes("₼0.00"))) return toast("Əvvəlcə alış qiymətlərini daxil edin."); document.querySelector("#detailStatus").value = "QUOTATION_SENT"; toast("Təklif statusu seçildi; yadda saxla düyməsinə basın."); };
    document.querySelectorAll(".remove-detail").forEach((button) => button.onclick = () => { const row = button.closest("tr"), index = Number(row.dataset.index); if (request.items.length <= 1) return toast("Sorğuda ən azı bir məhsul qalmalıdır."); request.items.splice(index, 1); audit("UPDATE", request.id); save(); fullDetail(id); toast("Məhsul sorğudan çıxarıldı"); });
    document.querySelector("#addDetailProduct").onclick = () => { const row = document.createElement("tr"); row.dataset.index = "-1"; row.innerHTML = `<td><input class="new-name" placeholder="Məhsul adı"><input class="new-qty" type="number" min="0.01" placeholder="Miqdar"></td><td class="qty-requested">0</td><td><input class="source-supplier" list="supplier-list" placeholder="Təchizatçı"></td><td><input class="source-found" type="number" min="0" value="0"></td><td><b class="source-left danger">0</b></td><td><input class="source-cost" type="number" min="0" step="0.0001" value="0"></td><td><input class="source-margin" type="number" min="0" value="20"></td><td><b class="source-sale">₼0.00</b></td><td><button class="secondary remove-detail" type="button">Sil</button></td>`; document.querySelector(".detail-prices tbody").append(row); row.querySelector(".new-qty").oninput = refresh; row.querySelector(".source-found").oninput = refresh; row.querySelector(".source-cost").oninput = refresh; row.querySelector(".source-margin").oninput = refresh; row.querySelector(".remove-detail").onclick = () => { row.remove(); refresh(); }; };
  }
  window.addEventListener("load", () => { window.detail = fullDetail; });
})();
