/* Request detail and price management layer for the local admin preview. */
(() => {
  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (x) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[x]));
  const suppliers = ["Azeri Fasteners", "Caspian Trade", "Steel Supply", "Baku Industrial"];
  const money = (value) => new Intl.NumberFormat("az-AZ", { style: "currency", currency: "AZN", maximumFractionDigits: 2 }).format(Number(value) || 0);
  const supplierOptions = (selected = "") => `<option value="">Təchizatçı seçin</option>${suppliers.map((s) => `<option ${s === selected ? "selected" : ""}>${s}</option>`).join("")}`;
  const total = (items, field) => items.reduce((sum, item) => sum + (Number(item.qty) || 0) * (Number(item[field]) || 0), 0);
  function openDetail(id) {
    const request = window.db.requests.find((item) => item.id === id); if (!request) return;
    const products = request.items.map((item, index) => `<tr data-index="${index}"><td><b>${esc(item.name)}</b><span class="muted">${item.unit || "ədəd"} · ${item.qty}</span></td><td><select class="price-supplier">${supplierOptions(item.supplier || "")}</select></td><td><input class="price-cost" type="number" min="0" step="0.0001" value="${item.cost || ""}" placeholder="0.00"></td><td><input class="price-sale" type="number" min="0" step="0.0001" value="${item.sale || ""}" placeholder="0.00"></td><td class="line-profit">${money((item.sale - item.cost) * item.qty)}</td><td><button type="button" class="secondary remove-item">Sil</button></td></tr>`).join("");
    window.modal(`<h2>${esc(request.id)} · ${esc(request.customer)}</h2><p class="muted">Sorğunun qiymət araşdırması, təchizatçı seçimi və təklif hazırlığı</p><div class="detail-grid"><div><small>Status</small>${window.badge(request.status)}</div><div><small>Prioritet</small>${esc(request.priority)}</div><div><small>Məhsul sayı</small>${request.items.length}</div></div><div class="table-wrap"><table class="tbl price-table"><thead><tr><th>Məhsul / miqdar</th><th>Təchizatçı</th><th>Alış qiyməti</th><th>Satış qiyməti</th><th>Mənfəət</th><th></th></tr></thead><tbody>${products}</tbody></table></div><button type="button" class="secondary" id="addRequestProduct" style="margin-top:12px">＋ Məhsul əlavə et</button><div id="requestTotals" class="result" style="margin-top:14px"></div><div class="field" style="margin-top:14px"><label>Status</label><select id="detailStatus">${["NEW", "PRICING", "QUOTATION_SENT", "WAITING_CUSTOMER", "ACTIVE", "COMPLETED", "REJECTED"].map((s) => `<option value="${s}" ${request.status === s ? "selected" : ""}>${window.statusText(s)}</option>`).join("")}</select></div><div class="actions"><button class="secondary" onclick="closeModal()">Bağla</button><button class="secondary" id="makeQuotation">Qiymət təklifi hazırla</button><button class="primary" id="savePrices">Qiymətləri saxla</button></div>`);
    const refresh = () => { let purchase = 0, sale = 0; document.querySelectorAll(".price-table tbody tr").forEach((row) => { const qty = Number(request.items[Number(row.dataset.index)]?.qty || row.querySelector(".new-qty")?.value || 0), cost = Number(row.querySelector(".price-cost")?.value || 0), sell = Number(row.querySelector(".price-sale")?.value || 0); purchase += qty * cost; sale += qty * sell; const profit = row.querySelector(".line-profit"); if (profit) profit.textContent = money(qty * (sell - cost)); }); document.querySelector("#requestTotals").innerHTML = `<b>Alış cəmi: ${money(purchase)}</b> &nbsp; <b>Satış cəmi: ${money(sale)}</b> &nbsp; <b class="${sale - purchase >= 0 ? "" : "danger"}">Mənfəət: ${money(sale - purchase)}</b>`; };
    document.querySelectorAll(".price-cost,.price-sale").forEach((el) => el.oninput = refresh); refresh();
    document.querySelectorAll(".remove-item").forEach((button) => button.onclick = () => { const row = button.closest("tr"), index = Number(row.dataset.index); if (request.items.length <= 1) return window.toast("Sorğuda ən azı bir məhsul qalmalıdır."); request.items.splice(index, 1); window.audit("UPDATE", request.id); window.save(); closeModal(); openDetail(id); window.toast("Məhsul sorğudan çıxarıldı"); });
    document.querySelector("#addRequestProduct").onclick = () => { const row = document.createElement("tr"); row.innerHTML = `<td><input class="new-name" placeholder="Məhsul adı"><input class="new-qty" type="number" min="0.01" placeholder="Miqdar"></td><td><select class="price-supplier">${supplierOptions()}</select></td><td><input class="price-cost" type="number" min="0" step="0.0001" placeholder="0.00"></td><td><input class="price-sale" type="number" min="0" step="0.0001" placeholder="0.00"></td><td class="line-profit">₼0.00</td><td><button type="button" class="secondary remove-new">Sil</button></td>`; row.dataset.index = "-1"; document.querySelector(".price-table tbody").append(row); row.querySelector(".price-cost").oninput = refresh; row.querySelector(".price-sale").oninput = refresh; row.querySelector(".new-qty").oninput = refresh; row.querySelector(".remove-new").onclick = () => { row.remove(); refresh(); }; };
    document.querySelector("#savePrices").onclick = () => { const rows = [...document.querySelectorAll(".price-table tbody tr")], next = []; for (const row of rows) { const index = Number(row.dataset.index), existing = index >= 0 ? request.items[index] : {}; const name = index >= 0 ? existing.name : row.querySelector(".new-name")?.value.trim(), qty = index >= 0 ? existing.qty : Number(row.querySelector(".new-qty")?.value); if (!name || !qty) return window.toast("Yeni məhsul üçün ad və miqdar yazın."); next.push({ ...existing, name, qty, unit: existing.unit || "ədəd", supplier: row.querySelector(".price-supplier")?.value || "", cost: Number(row.querySelector(".price-cost")?.value || 0), sale: Number(row.querySelector(".price-sale")?.value || 0) }); } request.items = next; const status = document.querySelector("#detailStatus").value; if (status !== request.status) { request.status = status; request.timeline.push("Status dəyişdi: " + window.statusText(status)); if (status === "ACTIVE") window.activate(request); } window.audit("PRICE_CHANGE", request.id); window.save(); closeModal(); window.render(); window.toast("Alış və satış qiymətləri saxlanıldı"); };
    document.querySelector("#makeQuotation").onclick = () => { const rows = [...document.querySelectorAll(".price-table tbody tr")]; if (rows.some((row) => !Number(row.querySelector(".price-sale")?.value))) return window.toast("Təklif üçün bütün satış qiymətlərini daxil edin."); document.querySelector("#detailStatus").value = "QUOTATION_SENT"; window.toast("Qiymət təklifi hazırlandı; yadda saxlamaq üçün qiymətləri saxla düyməsinə basın."); };
  }
  window.addEventListener("load", () => { const original = window.detail; window.detail = openDetail; window.openDetail = openDetail; });
})();
