import { AuditAction, InvoiceDirection, InvoiceStatus, MovementType, OrderStatus, Prisma, QuotationStatus, RequestStatus } from "@prisma/client";
import { db } from "@/lib/db"; import { audit } from "@/lib/audit";
const no=(prefix:string)=>`${prefix}-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;
/** Critical processes below use one database transaction: no partial inventory or finance states. */
export const orderService={
 async acceptQuotation(quotationId:string,userId:string){return db.$transaction(async tx=>{const q=await tx.quotation.findUniqueOrThrow({where:{id:quotationId},include:{items:true}});if(q.status!==QuotationStatus.SENT&&q.status!==QuotationStatus.VIEWED)throw new Error("Yalnız göndərilmiş təklif qəbul edilə bilər.");const salesOrder=await tx.salesOrder.create({data:{number:no("SO"),customerId:q.customerId,requestId:q.requestId,quotationId:q.id,status:OrderStatus.CONFIRMED,total:q.total,items:{create:q.items.map(i=>({productId:i.productId,description:i.description,quantity:i.quantity,unitId:i.unitId,salePrice:i.unitPrice,total:i.total}))}}});await tx.quotation.update({where:{id:q.id},data:{status:QuotationStatus.ACCEPTED}});await tx.request.update({where:{id:q.requestId},data:{status:RequestStatus.ACTIVE}});await tx.requestStatusHistory.create({data:{requestId:q.requestId,toStatus:RequestStatus.ACTIVE,changedById:userId,reason:"Təklif qəbul edildi"}});await audit.create({userId,action:AuditAction.APPROVE,module:"QUOTATIONS",entityType:"Quotation",entityId:q.id,newData:{salesOrderId:salesOrder.id,status:"ACCEPTED"}},tx);return salesOrder})},
 async confirmIncomingInvoice(invoiceId:string,userId:string){return db.$transaction(async tx=>{const invoice=await tx.invoice.findUniqueOrThrow({where:{id:invoiceId},include:{items:true}});if(invoice.direction!==InvoiceDirection.INCOMING||invoice.status!==InvoiceStatus.DRAFT)throw new Error("Yalnız qaralama gələn qaimə təsdiqlənə bilər.");const receipt=await tx.goodsReceipt.create({data:{number:no("GR"),purchaseOrderId:invoice.purchaseOrderId,warehouseId:invoice.warehouseId,items:{create:invoice.items.filter(i=>i.productId).map(i=>({productId:i.productId!,quantity:i.quantity,unitPrice:i.unitPrice}))}});for(const item of invoice.items){if(!item.productId)continue;const lot=await tx.stockLot.create({data:{number:no("LOT"),productId:item.productId,warehouseId:invoice.warehouseId,supplierId:invoice.supplierId,goodsReceiptId:receipt.id,quantityReceived:item.quantity,quantityRemaining:item.quantity,purchasePrice:item.unitPrice}});await tx.stockMovement.create({data:{warehouseId:invoice.warehouseId,productId:item.productId,type:MovementType.IN,quantity:item.quantity,referenceType:"IncomingInvoice",referenceId:invoice.id,userId}});await audit.create({userId,action:AuditAction.STOCK_IN,module:"WAREHOUSE",entityType:"StockLot",entityId:lot.id,newData:{invoiceId:invoice.id,quantity:item.quantity}},tx)}await tx.invoice.update({where:{id:invoiceId},data:{status:InvoiceStatus.CONFIRMED}});return receipt})},
 async confirmOutgoingInvoice(invoiceId:string,userId:string){return db.$transaction(async tx=>{const invoice=await tx.invoice.findUniqueOrThrow({where:{id:invoiceId},include:{items:true}});if(invoice.direction!==InvoiceDirection.OUTGOING||invoice.status!==InvoiceStatus.DRAFT)throw new Error("Yalnız qaralama gedən qaimə təsdiqlənə bilər.");for(const item of invoice.items){if(!item.productId)continue;let remaining=new Prisma.Decimal(item.quantity);const lots=await tx.stockLot.findMany({where:{productId:item.productId,warehouseId:invoice.warehouseId,quantityRemaining:{gt:0}},orderBy:{receivedDate:"asc"}});const movement=await tx.stockMovement.create({data:{warehouseId:invoice.warehouseId,productId:item.productId,type:MovementType.OUT,quantity:item.quantity,referenceType:"OutgoingInvoice",referenceId:invoice.id,userId}});for(const lot of lots){if(remaining.lte(0))break;const allocated=Prisma.Decimal.min(remaining,lot.quantityRemaining);await tx.stockLot.update({where:{id:lot.id},data:{quantityRemaining:{decrement:allocated}}});await tx.stockAllocation.create({data:{stockLotId:lot.id,stockMovementId:movement.id,quantity:allocated,unitCost:lot.purchasePrice}});remaining=remaining.minus(allocated)}if(remaining.gt(0))throw new Error(`${item.description} üçün kifayət qədər stok yoxdur.`)}await tx.invoice.update({where:{id:invoiceId},data:{status:InvoiceStatus.CONFIRMED}});await audit.create({userId,action:AuditAction.STOCK_OUT,module:"WAREHOUSE",entityType:"Invoice",entityId:invoiceId,newData:{status:"CONFIRMED"}},tx);return invoice})}
};
